name: mymacos-x64-cpu
on: [push, pull_request]
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: protobuf
      run: brew install protobuf opencv3
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -j 4
    - name: test
      run: cd build && ctest --output-on-failure -j 4
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./build/
